spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_tracker_db
    username: user76584930yr
    password: pasSw0rD6239ej
    hikari:
      schema: tracker
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
    contexts: dev
    default-schema: service